### ISSUE TITLE
Cannot initialise JS/TS language features in Vue project on VSCode

### ISSUE THREAD

**Issue by crevulus** [mediamonks/porter#11]
Steps to recreate:
1. run 'npx @mediamonks/porter create vue my-vue-app'
2. Open in VSCode
(3. Add TS syntax)

In the first screenshot below, you can see the in-built VSCode JS/TS language features extension is loading in the porter vue project (left) but has already leaded and therefore disappeared from the status bar in another project (right).

I also used porter to create a react skeleton project, and the language features initialised successfully.

In Screenshot #2 I've added a simple function with typed parameters, but my IDE doesn't recognise type declaration TS syntax. Presumably this is because it's failing to iniatilise those language features.

![Screenshot 2021-03-03 at 11 15 27](https://user-images.githubusercontent.com/50107046/109810324-b0675f00-7c29-11eb-8b2a-e002f8573a43.png)

![Screenshot 2021-03-03 at 11 16 04](https://user-images.githubusercontent.com/50107046/109807525-4dc09400-7c26-11eb-8b46-7e2cf6ab8fb7.png)

**Comment by psimk** [comment]
Should be fixed as part of https://github.com/mediamonks/porter/commit/764c6ff91ee0deed6c21ee578df65dbde9c4209b
