### ISSUE TITLE
ESLint ignoring unused imports in Vue

### ISSUE THREAD

**Issue by crevulus** [mediamonks/porter#12]
Steps to recreate:
1. Create a Vue project
2. Import but don't use a module

You can see in the screenshot below that I've imported the default `HelloWorld` component into a new `Test` component. Usually ESLint would flag that as a variable that has been declared but never used, but in this porter vue project ESLint doesn't complain at all.

I also initialised a multi-line, empty `props` object that wasn't flagged by ESLint at all.

![Screenshot 2021-03-03 at 11 16 23](https://user-images.githubusercontent.com/50107046/109807717-8fe9d580-7c26-11eb-8cff-38f3208c8ed4.png)

**Comment by psimk** [comment]
Should be fixed as part of https://github.com/mediamonks/porter/commit/764c6ff91ee0deed6c21ee578df65dbde9c4209b
