### ISSUE TITLE
Error while installing react skeleton

### ISSUE THREAD

**Issue by cobidev** [mediamonks/porter#13]
Hi @psimk 

I'm having an issue while trying to install the react skeleton.

I got: `Unexpected token '?'`

<img width="572" alt="Screen Shot 2021-04-19 at 18 09 45" src="https://user-images.githubusercontent.com/35739742/115303870-9383de00-a13a-11eb-9d00-2929ab7091c1.png">

I'm using:
Node 12.13.0
NPM version 6.14.4

**Comment by ThaNarie** [comment]
@cobidev I presume this does work in node 14? Most likely this is using the `?.` operator, which starts at node 14 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)

**Comment by cobidev** [comment]
@ThaNarie @psimk Yep!

It worked using node v14

Thanks :)

**Comment by psimk** [comment]
Node 12 should be supported from porter `v0.0.2-9`
